### PR TITLE
Allow bot accounts to create links or traces [BTA-832]

### PR DESCRIPTION
**Pull request by haroldcb**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/23)

### CODE REVIEW

**Review by conord33 — APPROVED** [review]
:lgtm: just some comments left around.

> Reviewed 10 of 10 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/23#-:-MXa745BBg5_Z04rtTvH:bi3u099)* status: all files reviewed, 4 unresolved discussions (waiting on @haroldcb and @Paturages)

___
*[src/test/java/com/stratumn/sdk/TestSdk.java, line 67 at r1](https://reviewable.io/reviews/stratumn/sdk-java/23#-MXa5lKJ9MT85YQOkSMS:-MXa5lKJ9MT85YQOkSMT:b-jrxcue) ([raw file](https://github.com/stratumn/sdk-java/blob/77ed60489420b209a8a989a62ec69858b3cd9b98/src/test/java/com/stratumn/sdk/TestSdk.java#L67)):*
> ```Java
>    private static final String MEDIA_URL = "https://media-api.staging.stratumn.com";
> 
>    // Java bot : public key = `-----BEGIN ED25519 PUBLIC KEY-----
> ```

comment
___
*[src/test/java/com/stratumn/sdk/TestSdk.java, line 81 at r1](https://reviewable.io/reviews/stratumn/sdk-java/23#-MXa5mt-CJzVW-LBDQ6M:-MXa5mt-CJzVW-LBDQ6N:b-jrxcue) ([raw file](https://github.com/stratumn/sdk-java/blob/77ed60489420b209a8a989a62ec69858b3cd9b98/src/test/java/com/stratumn/sdk/TestSdk.java#L81)):*
> ```Java
>    private static String MY_GROUP = "1744";
> 
>    // private static String PEM_PRIVATEKEY_2 = "-----BEGIN ED25519 PRIVATE
> ```

comment
___
*[src/test/java/com/stratumn/sdk/TestSdk.java, line 141 at r1](https://reviewable.io/reviews/stratumn/sdk-java/23#-MXa61NjEB6PCA1G_Byj:-MXa61NjEB6PCA1G_Byk:b-jrxcue) ([raw file](https://github.com/stratumn/sdk-java/blob/77ed60489420b209a8a989a62ec69858b3cd9b98/src/test/java/com/stratumn/sdk/TestSdk.java#L141)):*
> ```Java
>          GetTraceStateInput input = new GetTraceStateInput(traceId);
>          TraceState<Object, Object> state = sdk.getTraceState(input);
>          // // System.out.println("testTraceState" + gson.toJson(state));
> ```

comment
___
*[src/test/java/com/stratumn/sdk/TestSdkPojo.java, line 102 at r1](https://reviewable.io/reviews/stratumn/sdk-java/23#-MXa640j7iRmlDYueYYV:-MXa640j7iRmlDYueYYW:b-jrxcue) ([raw file](https://github.com/stratumn/sdk-java/blob/77ed60489420b209a8a989a62ec69858b3cd9b98/src/test/java/com/stratumn/sdk/TestSdkPojo.java#L102)):*
> ```Java
>    private static final String MEDIA_STAGING_URL = "https://media-api.staging.stratumn.com";
> 
>    // Java bot : public key = `-----BEGIN ED25519 PUBLIC KEY-----
> ```

comment

**Comment by haroldcb** [comment]
___
*[src/test/java/com/stratumn/sdk/TestSdk.java, line 141 at r1](https://reviewable.io/reviews/stratumn/sdk-java/23#-MXa61NjEB6PCA1G_Byj:-MXaN3EZCLgRZg227wTO:b-896fix) ([raw file](https://github.com/stratumn/sdk-java/blob/77ed60489420b209a8a989a62ec69858b3cd9b98/src/test/java/com/stratumn/sdk/TestSdk.java#L141)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

comment
</blockquote></details>

Done.

**Comment by haroldcb** [comment]
___
*[src/test/java/com/stratumn/sdk/TestSdk.java, line 81 at r1](https://reviewable.io/reviews/stratumn/sdk-java/23#-MXa5mt-CJzVW-LBDQ6M:-MXaN3vK9oJ-TljCtELc:b-896fix) ([raw file](https://github.com/stratumn/sdk-java/blob/77ed60489420b209a8a989a62ec69858b3cd9b98/src/test/java/com/stratumn/sdk/TestSdk.java#L81)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

comment
</blockquote></details>

Done.

**Comment by haroldcb** [comment]
___
*[src/test/java/com/stratumn/sdk/TestSdk.java, line 67 at r1](https://reviewable.io/reviews/stratumn/sdk-java/23#-MXa5lKJ9MT85YQOkSMS:-MXaN4ce1tW9vnz5os8X:b-896fix) ([raw file](https://github.com/stratumn/sdk-java/blob/77ed60489420b209a8a989a62ec69858b3cd9b98/src/test/java/com/stratumn/sdk/TestSdk.java#L67)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

comment
</blockquote></details>

Done.

**Comment by haroldcb** [comment]
___
*[src/test/java/com/stratumn/sdk/TestSdkPojo.java, line 102 at r1](https://reviewable.io/reviews/stratumn/sdk-java/23#-MXa640j7iRmlDYueYYV:-MXaNGxT912hNvAZvlDj:b-896fix) ([raw file](https://github.com/stratumn/sdk-java/blob/77ed60489420b209a8a989a62ec69858b3cd9b98/src/test/java/com/stratumn/sdk/TestSdkPojo.java#L102)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

comment
</blockquote></details>

Done.

**Comment by haroldcb** [comment]
I removed the "TestSdk" Class to keep only the "TestSdkPojo" one.
I also removed the main in the class because all of it got covered in other tests.

**Review by conord33 — COMMENTED** [review]
> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/23)* status: all files reviewed, 1 unresolved discussion (waiting on @haroldcb and @Paturages)

___
*[src/test/java/com/stratumn/sdk/TestSdk.java, line 466 at r1](https://reviewable.io/reviews/stratumn/sdk-java/23#-MXblEOYCPdqGiEr98hP:-MXblEOYCPdqGiEr98hQ:b-yu2kdg) ([raw file](https://github.com/stratumn/sdk-java/blob/77ed60489420b209a8a989a62ec69858b3cd9b98/src/test/java/com/stratumn/sdk/TestSdk.java#L466)):*
> ```Java
>       // push to accept
>       data = new HashMap<String, Object>(Collections.singletonMap("why", "because im testing the pushTrace 2"));
>       push = new PushTransferInput<Object>(MY_GROUP, data, state.getTraceId());
> ```

looks like `MY_GROUP` is no longer used in test file that was kept. was it just used to test deprecated methods?

**Comment by haroldcb** [comment]
___
*[src/test/java/com/stratumn/sdk/TestSdk.java, line 466 at r1](https://reviewable.io/reviews/stratumn/sdk-java/23#-MXblEOYCPdqGiEr98hP:-MXbm56R-2dQf5AvjVEn:b-fz23ok) ([raw file](https://github.com/stratumn/sdk-java/blob/77ed60489420b209a8a989a62ec69858b3cd9b98/src/test/java/com/stratumn/sdk/TestSdk.java#L466)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

looks like `MY_GROUP` is no longer used in test file that was kept. was it just used to test deprecated methods?
</blockquote></details>

I think so, the other one get the group from the api call

**Review by Paturages — APPROVED** [review]
> Reviewed 8 of 10 files at r1, 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/23)* status: all files reviewed, 1 unresolved discussion (waiting on @conord33)

**Comment by haroldcb** [comment]
___
*[src/test/java/com/stratumn/sdk/TestSdk.java, line 466 at r1](https://reviewable.io/reviews/stratumn/sdk-java/23#-MXblEOYCPdqGiEr98hP:-MXfXC_gCoNUlbwENd29:bb6un1j) ([raw file](https://github.com/stratumn/sdk-java/blob/77ed60489420b209a8a989a62ec69858b3cd9b98/src/test/java/com/stratumn/sdk/TestSdk.java#L466)):*
<details><summary><i>Previously, haroldcb wrote…</i></summary><blockquote>

I think so, the other one get the group from the api call
</blockquote></details>

Done

**Review by conord33 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/23)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haroldcb)

**Review by conord33 — APPROVED** [review]
:lgtm_strong: We should make sure that the major and minor versions always match across the sdks. Otherwise we are probably doing something wrong :joy: 

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/23#-:-MXgcuBn1-VN4Tx9QYaw:b4u9yhx)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @haroldcb)

**Pull request merged**
