### PR TITLE
Prepare release 2.2.0

### PR DESCRIPTION
**Pull request by conord33**
@Paturages let me know if you have done this, but I am pretty sure we need to manually bump the version like this.

---
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/26)

### CODE REVIEW

**Review by haroldcb — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/26)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @Paturages)

**Review by Paturages — APPROVED** [review]
0.0.13 to 2.2.0 is a big bump lol, but I haven't touched sdk-java nor Maven unfortunately

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/26#-:-MZHXKWkAtCOo50pjBYb:b-ocmei8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @conord33)

**Review by conord33 — COMMENTED** [review]
Haha yeah it s big one. the idea is to have all the sdk on the same minor version, since they should all have the same functionality and api

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/26#-:-MZHa7qBB9ljGQsqOXsS:b-pgs6jv)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @conord33)

**Review by Paturages — COMMENTED** [review]
makes sense, good call :+1: 

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/26#-:-MZHirSb9_j5Ejt_G1al:b6cf5et)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @conord33)

**Review by conord33 — COMMENTED** [review]
i am gonna wait to merge this till we know for sure that sdk-js is 2.2

> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/26#-:-MZHnoeM3Vk_LhuCrn3A:b-958626)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @conord33)

**Pull request merged**
