### PR TITLE
Improve search feature to search by tag in a "AND" or "OR" way[BTA-912]

### PR DESCRIPTION
**Pull request by haroldcb**
This change is [Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/24)

### CODE REVIEW

**Review by Paturages — APPROVED** [review]
:lgtm:

> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/24#-:-MY5c2ID1vVCF9DhohtX:bnfp4nl)* status: all files reviewed, 2 unresolved discussions (waiting on @conord33 and @haroldcb)

___
*[README.md, line 125 at r1](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5Twq0A0oquGwCL6EU:-MY5Twq13-DuKczmeOu0:boo6axq) ([raw file](https://github.com/stratumn/sdk-java/blob/b316d0699cb378ea77166c34c631223502126aa1/README.md#L125)):*
> ```Markdown
> You must provide:
> 
> - `actionKey`: a valid form id,
> ```

nit: a valid action key that exists in the targeted workflow
___
*[README.md, line 237 at r1](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5Wrtt4-VSZ-nEu4u6:-MY5Wrtt4-VSZ-nEu4u7:b-t6zhzm) ([raw file](https://github.com/stratumn/sdk-java/blob/b316d0699cb378ea77166c34c631223502126aa1/README.md#L237)):*
> ```Markdown
> tags.add("todo");
> tags.add("other tag");
> SearchTracesFilter f = new SearchTracesFilter(tags);
> ```

nit: I assume that the `SearchTracesFilter.SEARCH_TYPE.TAGS_OVERLAPS` argument is implicit and by default, which would be good to explicit here probably (in contrast to the "contains" type)

**Comment by haroldcb** [comment]
___
*[README.md, line 237 at r1](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5Wrtt4-VSZ-nEu4u6:-MY5cvL3-Lx_-QQwl6h7:bv92h6c) ([raw file](https://github.com/stratumn/sdk-java/blob/b316d0699cb378ea77166c34c631223502126aa1/README.md#L237)):*
<details><summary><i>Previously, Paturages (Paturages) wrote…</i></summary><blockquote>

nit: I assume that the `SearchTracesFilter.SEARCH_TYPE.TAGS_OVERLAPS` argument is implicit and by default, which would be good to explicit here probably (in contrast to the "contains" type)
</blockquote></details>

Yes by default it will be `TAGS_OVERLAPS` to keep the current behavior.
I will add a line about it :)

**Review by conord33 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/24)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @haroldcb and @Paturages)

___
*[README.md, line 11 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5y3sE91cMAjX8h_vx:-MY5y3sE91cMAjX8h_vy:bb7fvrr) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L11)):*
> ```Markdown
> ### Maven
> 
> ```xml
> ```

ewww
___
*[README.md, line 239 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5yYap2UKjeSREP5Ut:-MY5yYap2UKjeSREP5Uu:b-pl8746) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L239)):*
> ```Markdown
> SearchTracesFilter f = new SearchTracesFilter(tags);
> // Which is the same as :
> // SearchTracesFilter f = new SearchTracesFilter(tags, SearchTracesFilter.SEARCH_TYPE.TAGS_OVERLAPS);
> ```

i think it might be cleaner to add a method on the `SearchTracesFilter` class rather than adding an argument to the constructor. seems to be more inline with how we add tags using the `AddTagsToTraceInput` class. I think this way is a bit more resistant to breaking changes as well if we decide to add something later. (We should make sure c# follows the same pattern)

@paturages wdyt?

**Comment by haroldcb** [comment]
___
*[README.md, line 11 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5y3sE91cMAjX8h_vx:-MY92PSK54GSRY9edUf5:bs2c5hb) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L11)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

ewww
</blockquote></details>

What ? :sweat_smile:

**Comment by haroldcb** [comment]
___
*[README.md, line 239 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5yYap2UKjeSREP5Ut:-MY93VP86SbPUAXOiG_F:buh7h63) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L239)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

i think it might be cleaner to add a method on the `SearchTracesFilter` class rather than adding an argument to the constructor. seems to be more inline with how we add tags using the `AddTagsToTraceInput` class. I think this way is a bit more resistant to breaking changes as well if we decide to add something later. (We should make sure c# follows the same pattern)

@paturages wdyt?
</blockquote></details>

I'm not sure about the method you're thinking about ?
I created a new constructor with arguments, which is called by the default one (without arguments).
As the filters are an object, I thought it was easier to pass the list of tags and the type of search we wanted directly in the constructor.
This could be extended to other type of search if needed.
@paturages let me know what you think :)

**Review by conord33 — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/24)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @haroldcb and @Paturages)

___
*[README.md, line 11 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5y3sE91cMAjX8h_vx:-MY9F8khCkMNh_XbY3ET:byuho88) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L11)):*
<details><summary><i>Previously, haroldcb wrote…</i></summary><blockquote>

What ? :sweat_smile:
</blockquote></details>

just xml
___
*[README.md, line 239 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5yYap2UKjeSREP5Ut:-MY9FJd1CoNkx-taUWIZ:b-pejmy0) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L239)):*
This is what we have for adding tags. So rather than using a constructor we use methods to update the object.

> ```
> AddTagsToTraceInput input = new AddTagsToTraceInput();
> input.setTraceId(traceId);
> input.setTags(new String[] { "todo", "other tag" });
> ```

Obviously for searching we cannot remove the tags from the constructor because it would be breaking, but we can use methods for new fields. We could even make the tags in the constructor optional and encourage users to use a method to add tags instead. I think this helps make the api of the sdk more consistent and future proof.

**Comment by haroldcb** [comment]
___
*[README.md, line 239 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5yYap2UKjeSREP5Ut:-MY9Lw-EDrn4vsjVOl6t:b23p79e) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L239)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

This is what we have for adding tags. So rather than using a constructor we use methods to update the object.

> ```
> AddTagsToTraceInput input = new AddTagsToTraceInput();
> input.setTraceId(traceId);
> input.setTags(new String[] { "todo", "other tag" });
> ```

Obviously for searching we cannot remove the tags from the constructor because it would be breaking, but we can use methods for new fields. We could even make the tags in the constructor optional and encourage users to use a method to add tags instead. I think this helps make the api of the sdk more consistent and future proof.
</blockquote></details>

There is also a constructor with parameters which could be easier to use :
```java
public AddTagsToTraceInput(String traceId, String[] tags)
   {
      super();
      this.traceId = traceId;
      this.tags = tags;
   }
```
The problem here is that I changed the "List<String> tags;" to "Map<String, Object> filters" in order to integrate the building of the filter object in the "SearchTracesFilter" class.
So I can do it this way but I think constructors are the best way to do it no ?

**Review by Paturages — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/24)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @conord33, @haroldcb, and @Paturages)

___
*[README.md, line 11 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5y3sE91cMAjX8h_vx:-MY9OP1m-2dQnpJ2CIaj:b-tmuyzt) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L11)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

just xml
</blockquote></details>

:see_no_evil: 
___
*[README.md, line 239 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5yYap2UKjeSREP5Ut:-MY9Oh2VDDEMnbXhX42F:b-t4zbkc) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L239)):*
<details><summary><i>Previously, haroldcb wrote…</i></summary><blockquote>

There is also a constructor with parameters which could be easier to use :
```java
public AddTagsToTraceInput(String traceId, String[] tags)
   {
      super();
      this.traceId = traceId;
      this.tags = tags;
   }
```
The problem here is that I changed the "List<String> tags;" to "Map<String, Object> filters" in order to integrate the building of the filter object in the "SearchTracesFilter" class.
So I can do it this way but I think constructors are the best way to do it no ? 
</blockquote></details>

it probably makes more explicit sense in the code as
```java
SearchTracesFilter f = new SearchTracesFilter(new String[] { "todo", "other tag" });
// By default, the filter mode is set to "overlap", which checks for any matching tag
f.setSearchType(SearchTracesFilter.SEARCH_TYPE.TAGS_OVERLAPS);
// The "contains" filter is available to check for traces that match all provided tags
f.setSearchType(SearchTracesFilter.SEARCH_TYPE.TAGS_CONTAINS);
```

perhaps even
```java
SearchTracesFilter f = new SearchTracesFilter();
// Define tags
f.setTags(new String[] { "todo", "other tag" });
// By default, the filter mode is set to "overlap", which checks for any matching tag
f.setSearchType(SearchTracesFilter.SEARCH_TYPE.TAGS_OVERLAPS);
// The "contains" filter is available to check for traces that match all provided tags
f.setSearchType(SearchTracesFilter.SEARCH_TYPE.TAGS_CONTAINS);
```

which I think is more extensible if we decide to add search by trace state in the SDKs for example (which might be more recommendable in the future)

**Review by Paturages — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/24)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @conord33, @haroldcb, and @Paturages)

___
*[README.md, line 239 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5yYap2UKjeSREP5Ut:-MY9QfStD23xk-nL4SCP:b-ictyl7) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L239)):*
<details><summary><i>Previously, Paturages (Paturages) wrote…</i></summary><blockquote>

it probably makes more explicit sense in the code as
```java
SearchTracesFilter f = new SearchTracesFilter(new String[] { "todo", "other tag" });
// By default, the filter mode is set to "overlap", which checks for any matching tag
f.setSearchType(SearchTracesFilter.SEARCH_TYPE.TAGS_OVERLAPS);
// The "contains" filter is available to check for traces that match all provided tags
f.setSearchType(SearchTracesFilter.SEARCH_TYPE.TAGS_CONTAINS);
```

perhaps even
```java
SearchTracesFilter f = new SearchTracesFilter();
// Define tags
f.setTags(new String[] { "todo", "other tag" });
// By default, the filter mode is set to "overlap", which checks for any matching tag
f.setSearchType(SearchTracesFilter.SEARCH_TYPE.TAGS_OVERLAPS);
// The "contains" filter is available to check for traces that match all provided tags
f.setSearchType(SearchTracesFilter.SEARCH_TYPE.TAGS_CONTAINS);
```

which I think is more extensible if we decide to add search by trace state in the SDKs for example (which might be more recommendable in the future)
</blockquote></details>

the additional thing about the latter syntax is that everything is explicit and you don't have to remember (or have your IDE tell you) what the arguments for the constructor are and/or in which order they should be

**Comment by haroldcb** [comment]
___
*[README.md, line 239 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5yYap2UKjeSREP5Ut:-MY9Z7Rs-MiTg7dJ4FfZ:b9ldz22) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L239)):*
<details><summary><i>Previously, Paturages (Paturages) wrote…</i></summary><blockquote>

the additional thing about the latter syntax is that everything is explicit and you don't have to remember (or have your IDE tell you) what the arguments for the constructor are and/or in which order they should be
</blockquote></details>

I see that's better ! 
And what about a list of "searchTypes" that would be combined ? For example "TAGS_OVERLAPS and TAGS_CONTAINS" could be combined in the search ?
This would prevent breaking change in the future ?

**Review by conord33 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/24)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @conord33, @haroldcb, and @Paturages)

___
*[README.md, line 239 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5yYap2UKjeSREP5Ut:-MY9brl7-PoQK1h38IGc:b-eqk4sr) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L239)):*
<details><summary><i>Previously, haroldcb wrote…</i></summary><blockquote>

I see that's better ! 
And what about a list of "searchTypes" that would be combined ? For example "TAGS_OVERLAPS and TAGS_CONTAINS" could be combined in the search ?
This would prevent breaking change in the future ?
</blockquote></details>

i am not quite sure how those could be combined though? wouldn't overlaps or contains need to be one or the other?

**Comment by haroldcb** [comment]
___
*[README.md, line 239 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5yYap2UKjeSREP5Ut:-MY9cZlK9Dk0WsGYMg5W:bxqkcsd) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L239)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

i am not quite sure how those could be combined though? wouldn't overlaps or contains need to be one or the other?
</blockquote></details>

It was a bad example, but I don't know if the case could happen in the future ?

**Review by conord33 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/24)* status: 3 of 4 files reviewed, 4 unresolved discussions (waiting on @conord33, @haroldcb, and @Paturages)

___
*[README.md, line 239 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5yYap2UKjeSREP5Ut:-MY9hW0L8gmMbiRqdXsv:bxna946) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L239)):*
<details><summary><i>Previously, haroldcb wrote…</i></summary><blockquote>

It was a bad example, but I don't know if the case could happen in the future ?
</blockquote></details>

yes i think it possible to have a more complicated query in the future like `a and b or c and d` but i think we would need to make a bigger change to the api in that case. in this case though we could either add more methods to configure a query like that, or add a new method entirely. but it would be hard to keep adding new things like that to the constructor.

**Comment by haroldcb** [comment]
___
*[README.md, line 239 at r2](https://reviewable.io/reviews/stratumn/sdk-java/24#-MY5yYap2UKjeSREP5Ut:-MYA2H165Tlb7v0FXCUc:bxy7tcf) ([raw file](https://github.com/stratumn/sdk-java/blob/a173a54c5a7c103296810ae2f39c53a0f6c6886e/README.md#L239)):*
<details><summary><i>Previously, conord33 (Conor Dawson) wrote…</i></summary><blockquote>

yes i think it possible to have a more complicated query in the future like `a and b or c and d` but i think we would need to make a bigger change to the api in that case. in this case though we could either add more methods to configure a query like that, or add a new method entirely. but it would be hard to keep adding new things like that to the constructor.
</blockquote></details>

Ok I did the change, let me know if it is ok with what you meant ?

**Review by conord33 — APPROVED** [review]
:lgtm: just one comment on the if else structure

> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/24#-:-MYAByxs8kCwSFGhnXT_:b-s3oww1)* status: all files reviewed, 5 unresolved discussions (waiting on @conord33, @haroldcb, and @Paturages)

___
*[src/main/java/com/stratumn/sdk/model/trace/SearchTracesFilter.java, line 50 at r3](https://reviewable.io/reviews/stratumn/sdk-java/24#-MYABhVj4uUibkkO2G4F:-MYABhVkDZqnyPZLGiGn:brxeymg) ([raw file](https://github.com/stratumn/sdk-java/blob/90b7ce6e26809f4e606db4b2128217767049c2bd/src/main/java/com/stratumn/sdk/model/trace/SearchTracesFilter.java#L50)):*
> ```Java
>     Map<String, Object> searchFilter = new HashMap<String, Object>();
> 
>     if (null == this.searchType) {
> ```

i think you can simplify this block with just an if else. if its not explicitly set to `TAG_CONTAINS` then its `TAG_OVERLAPS`

**Review by Paturages — APPROVED** [review]
> Reviewed 1 of 3 files at r3, 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/stratumn/sdk-java/24)* status: all files reviewed, 5 unresolved discussions (waiting on @conord33, @haroldcb, and @Paturages)

**Pull request merged**
